<a href="https://colab.research.google.com/github/prakashrock0510-ni/First_project/blob/main/project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import requests
import pandas as pd
from datetime import datetime

In [3]:
all_records = []
start_year = datetime.now().year - 5   # last 5 years
end_year = datetime.now().year

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

In [4]:
for year in range(start_year, end_year + 1) :
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        response = requests.get(url, params=params)
        if response.status_code != 200:
            print(f"⚠️ Failed for {start_date}: {response.text[:200]}")
            continue

        try:
            data = response.json()
        except Exception as e:
            print(f"⚠️ JSON error for {start_date}: {e}")
            continue

        for f in data["features"]:
            p = f["properties"]
            g = f["geometry"]["coordinates"]
            all_records.append({
                "id": f.get("id"),
                "time": pd.to_datetime(p.get("time"), unit="ms"),
                "updated": pd.to_datetime(p.get("updated"), unit="ms"),
                "latitude": g[1] if g else None,
                "longitude": g[0] if g else None,
                "depth_km": g[2] if g else None,
                "mag": p.get("mag"),
                "magType": p.get("magType"),
                "place" :p.get("place"),
                "status":p.get("status"),
                "tsunami":p.get("tsunami"),
                "alert":p.get("alert"),
                "felt":p.get("felt"),
                "cdi":p.get("cdi"),
                "mmi":p.get("mmi"),
                "sig":p.get("sig"),
                "net":p.get("net"),
                "code":p.get("code"),
                "ids":p.get("ids"),
                "magNst":p.get("magNst"),
                "magscore":p.get("magscore"),
                "magerror":p.get("magrror"),
                "deptherror":p.get("depthError"),
                "sources":p.get("sources"),
                "types":p.get("types"),
                "nst":p.get("nst"),
                "dmin":p.get("dmin"),
                "rms":p.get("rms"),
                "gap":p.get("gap"),
                "type":p.get("type")
            })


df = pd.DataFrame(all_records)

print("rows :",df.shape[0])
print("columns:",df.shape[1])
print(df.head())

rows : 119331
columns: 30
           id                    time                 updated  latitude  \
0  us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040  -31.7493
1  us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040  -15.4902
2  us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040   19.7529
3  us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040   28.1524
4  us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040   71.3212

   longitude  depth_km  mag magType  \
0   -68.9337     17.27  4.7     mwr
1  -177.2052    426.71  4.1      mb
2   121.3159     46.73  4.7      mb
3    57.2570     10.00  4.9      mb
4    -3.7578     10.00  4.0      mb

                                               place    status  ...  magscore  \
0        29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...      None
1                                        Fiji region  reviewed  ...      None
2                    103 km SW of Basco, Philippines  reviewed  ...      None
3                            114 km N of M?n?b, Iran  reviewed  ...      None
4  184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...      None

  magerror  deptherror  sources                                   types  nst  \
0     None        None     ,us,  ,dyfi,moment-tensor,origin,phase-data,  NaN
1     None        None     ,us,                     ,origin,phase-data,  NaN
2     None        None     ,us,                     ,origin,phase-data,  NaN
3     None        None     ,us,                     ,origin,phase-data,  NaN
4     None        None     ,us,                     ,origin,phase-data,  NaN

    dmin   rms    gap        type
0  0.294  0.82   42.0  earthquake
1  1.471  0.29   64.0  earthquake
2  3.057  0.69  106.0  earthquake
3  3.330  0.61   71.0  earthquake
4  6.023  0.50   65.0  earthquake

[5 rows x 30 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119331 entries, 0 to 119330
Data columns (total 30 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          119331 non-null  object
 1   time        119331 non-null  datetime64[ns]
 2   updated     119331 non-null  datetime64[ns]
 3   latitude    119331 non-null  float64
 4   longitude   119331 non-null  float64
 5   depth_km    119331 non-null  float64
 6   mag         119331 non-null  float64
 7   magType     119331 non-null  object
 8   place       119331 non-null  object
 9   status      119331 non-null  object
 10  tsunami     119331 non-null  int64
 11  alert       4876 non-null    object
 12  felt        18153 non-null   float64
 13  cdi         18153 non-null   float64
 14  mmi         10557 non-null   float64
 15  sig         119331 non-null  int64
 16  net         119331 non-null  object
 17  code        119331 non-null  object
 18  ids         119331 non-null  object
 19  magNst      0 non-null       object
 20  magscore    0 non-null       object
 21  magerror    0 non-null       object
 22  deptherror  0 non-null       object
 23  sources     119331 non-null  object
 24  types       119331 non-null  object
 25  nst         91569 non-null   float64
 26  dmin        115353 non-null  float64
 27  rms         119312 non-null  float64
 28  gap         116307 non-null  float64
 29  type        119331 non-null  object
dtypes: datetime64[ns](2), float64(11), int64(2), object(15)
memory usage: 27.3+ MB

In [6]:
df['alert'] = df['alert'].fillna(df['alert'].mode()[0])

In [7]:
df.isnull().sum()

id                 0
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert              0
felt          101178
cdi           101178
mmi           108774
sig                0
net                0
code               0
ids                0
magNst        119331
magscore      119331
magerror      119331
deptherror    119331
sources            0
types              0
nst            27762
dmin            3978
rms               19
gap             3024
type               0
dtype: int64

In [8]:
df['gap'] =df['gap'].fillna(df['gap'].mean())

In [9]:
df.isnull().sum()

id                 0
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert              0
felt          101178
cdi           101178
mmi           108774
sig                0
net                0
code               0
ids                0
magNst        119331
magscore      119331
magerror      119331
deptherror    119331
sources            0
types              0
nst            27762
dmin            3978
rms               19
gap                0
type               0
dtype: int64

In [10]:
print(df)

                   id                    time                 updated  \
0          us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040
1          us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040
2          us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040
3          us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040
4          us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040
...               ...                     ...                     ...
119326     us7000tdbz 2026-09-01 04:50:45.457 2026-09-01 20:23:31.864
119327  aka2026rhblzv 2026-09-01 03:04:24.961 2026-09-01 16:13:24.871
119328     pr71530493 2026-09-01 03:03:51.600 2026-09-01 09:34:39.270
119329     us7000td94 2026-09-01 02:22:48.557 2026-09-01 16:08:36.998
119330     us7000td8u 2026-09-01 01:29:10.774 2026-09-01 01:44:48.040

        latitude  longitude  depth_km   mag magType  \
0       -31.7493   -68.9337    17.270  4.70     mwr
1       -15.4902  -177.2052   426.710  4.10      mb
2        19.7529   121.3159    46.730  4.70      mb
3        28.1524    57.2570    10.000  4.90      mb
4        71.3212    -3.7578    10.000  4.00      mb
...          ...        ...       ...   ...     ...
119326    8.6353   -82.4204    10.000  3.60      ml
119327   51.4140  -177.0380    40.200  3.00      ml
119328   18.4445   -68.2475    93.890  3.42      md
119329   55.9965  -161.1496   192.579  3.30      ml
119330  -20.4066  -177.9940   533.035  4.80      mb

                                                    place    status  ...  \
0             29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...
1                                             Fiji region  reviewed  ...
2                         103 km SW of Basco, Philippines  reviewed  ...
3                                 114 km N of M?n?b, Iran  reviewed  ...
4       184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...
...                                                   ...       ...  ...
119326                        4 km WSW of Caldera, Panama  reviewed  ...
119327                          58 km SSW of Adak, Alaska  reviewed  ...
119328         22 km SE of Punta Cana, Dominican Republic  reviewed  ...
119329                    3 km E of Nelson Lagoon, Alaska  reviewed  ...
119330                         292 km WNW of Houma, Tonga  reviewed  ...

        magscore magerror  deptherror  sources  \
0           None     None        None     ,us,
1           None     None        None     ,us,
2           None     None        None     ,us,
3           None     None        None     ,us,
4           None     None        None     ,us,
...          ...      ...         ...      ...
119326      None     None        None     ,us,
119327      None     None        None     ,ak,
119328      None     None        None     ,pr,
119329      None     None        None  ,ak,us,
119330      None     None        None     ,us,

                                         types   nst    dmin   rms    gap  \
0       ,dyfi,moment-tensor,origin,phase-data,   NaN  0.2940  0.82   42.0
1                          ,origin,phase-data,   NaN  1.4710  0.29   64.0
2                          ,origin,phase-data,   NaN  3.0570  0.69  106.0
3                          ,origin,phase-data,   NaN  3.3300  0.61   71.0
4                          ,origin,phase-data,   NaN  6.0230  0.50   65.0
...                                        ...   ...     ...   ...    ...
119326                ,dyfi,origin,phase-data,   6.0  1.0260  0.38  225.0
119327                     ,origin,phase-data,  26.0  0.4000  0.50  213.0
119328                     ,origin,phase-data,  13.0  0.1445  0.41  176.0
119329                     ,origin,phase-data,  16.0  0.6760  0.61  132.0
119330                     ,origin,phase-data,  69.0  4.5810  1.00   63.0

              type
0       earthquake
1       earthquake
2       earthquake
3       earthquake
4       earthquake
...            ...
119326  earthquake
119327  earthquake
119328  earthquake
119329  earthquake
119330  earthquake

[119331 rows x 30 columns]

In [11]:
df['mmi'].dtype

dtype('float64')

In [12]:
df.isnull().sum()

id                 0
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert              0
felt          101178
cdi           101178
mmi           108774
sig                0
net                0
code               0
ids                0
magNst        119331
magscore      119331
magerror      119331
deptherror    119331
sources            0
types              0
nst            27762
dmin            3978
rms               19
gap                0
type               0
dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [13]:
df['felt']=df['felt'].fillna(df['felt'].median)

In [14]:
df.isnull().sum()

id                 0
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert              0
felt               0
cdi           101178
mmi           108774
sig                0
net                0
code               0
ids                0
magNst        119331
magscore      119331
magerror      119331
deptherror    119331
sources            0
types              0
nst            27762
dmin            3978
rms               19
gap                0
type               0
dtype: int64

In [15]:
df['nst'].sample(100)

107082    23.0
91872     94.0
51463     59.0
63898     96.0
31554     31.0
          ...
29160      NaN
52564     21.0
31291     30.0
95534     12.0
103007    24.0
Name: nst, Length: 100, dtype: float64

In [16]:
df['nst']=df['nst'].fillna(df['nst'].median)

In [17]:
df.isnull().sum()

id                 0
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert              0
felt               0
cdi           101178
mmi           108774
sig                0
net                0
code               0
ids                0
magNst        119331
magscore      119331
magerror      119331
deptherror    119331
sources            0
types              0
nst                0
dmin            3978
rms               19
gap                0
type               0
dtype: int64

In [18]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
df[["rms"]] = imputer.fit_transform(df[["rms"]])

In [19]:
df.isnull().sum()

id                 0
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert              0
felt               0
cdi           101178
mmi           108774
sig                0
net                0
code               0
ids                0
magNst        119331
magscore      119331
magerror      119331
deptherror    119331
sources            0
types              0
nst                0
dmin            3978
rms                0
gap                0
type               0
dtype: int64

In [20]:
df.shape

(119331, 30)

In [21]:
df['cdi']=df['cdi'].fillna(df['cdi'].median())

In [22]:
df.isnull().sum()

id                 0
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert              0
felt               0
cdi                0
mmi           108774
sig                0
net                0
code               0
ids                0
magNst        119331
magscore      119331
magerror      119331
deptherror    119331
sources            0
types              0
nst                0
dmin            3978
rms                0
gap                0
type               0
dtype: int64

In [23]:
df=df.drop(columns=['mmi'])

In [24]:
df.isnull().sum()

id                 0
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert              0
felt               0
cdi                0
sig                0
net                0
code               0
ids                0
magNst        119331
magscore      119331
magerror      119331
deptherror    119331
sources            0
types              0
nst                0
dmin            3978
rms                0
gap                0
type               0
dtype: int64

In [25]:
df.shape

(119331, 29)

In [26]:
df["time"]=pd.to_datetime(df["time"])

In [27]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,magscore,magerror,deptherror,sources,types,nst,dmin,rms,gap,type
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.270,4.70,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,None,None,None,",us,",",dyfi,moment-tensor,origin,phase-data,",<bound method Series.median of 0 NaN\...,0.2940,0.82,42.0,earthquake
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.710,4.10,mb,Fiji region,reviewed,...,None,None,None,",us,",",origin,phase-data,",<bound method Series.median of 0 NaN\...,1.4710,0.29,64.0,earthquake
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.730,4.70,mb,"103 km SW of Basco, Philippines",reviewed,...,None,None,None,",us,",",origin,phase-data,",<bound method Series.median of 0 NaN\...,3.0570,0.69,106.0,earthquake
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.000,4.90,mb,"114 km N of M?n?b, Iran",reviewed,...,None,None,None,",us,",",origin,phase-data,",<bound method Series.median of 0 NaN\...,3.3300,0.61,71.0,earthquake
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.000,4.00,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,None,None,None,",us,",",origin,phase-data,",<bound method Series.median of 0 NaN\...,6.0230,0.50,65.0,earthquake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119326,us7000tdbz,2026-09-01 04:50:45.457,2026-09-01 20:23:31.864,8.6353,-82.4204,10.000,3.60,ml,"4 km WSW of Caldera, Panama",reviewed,...,None,None,None,",us,",",dyfi,origin,phase-data,",6.0,1.0260,0.38,225.0,earthquake
119327,aka2026rhblzv,2026-09-01 03:04:24.961,2026-09-01 16:13:24.871,51.4140,-177.0380,40.200,3.00,ml,"58 km SSW of Adak, Alaska",reviewed,...,None,None,None,",ak,",",origin,phase-data,",26.0,0.4000,0.50,213.0,earthquake
119328,pr71530493,2026-09-01 03:03:51.600,2026-09-01 09:34:39.270,18.4445,-68.2475,93.890,3.42,md,"22 km SE of Punta Cana, Dominican Republic",reviewed,...,None,None,None,",pr,",",origin,phase-data,",13.0,0.1445,0.41,176.0,earthquake
119329,us7000td94,2026-09-01 02:22:48.557,2026-09-01 16:08:36.998,55.9965,-161.1496,192.579,3.30,ml,"3 km E of Nelson Lagoon, Alaska",reviewed,...,None,None,None,",ak,us,",",origin,phase-data,",16.0,0.6760,0.61,132.0,earthquake
119330,us7000td8u,2026-09-01 01:29:10.774,2026-09-01 01:44:48.040,-20.4066,-177.9940,533.035,4.80,mb,"292 km WNW of Houma, Tonga",reviewed,...,None,None,None,",us,",",origin,phase-data,",69.0,4.5810,1.00,63.0,earthquake

In [28]:
df["Year"] = df["time"].dt.year
df["month"] = df["time"].dt.month
df["day"] = df["time"].dt.day
df["day_of_week"] = df["time"].dt.day_name()

print(df[["time", "Year", "month", "day", "day_of_week"]].head())

                     time  Year  month  day day_of_week
0 2021-01-31 23:20:49.923  2021      1   31      Sunday
1 2021-01-31 23:08:17.161  2021      1   31      Sunday
2 2021-01-31 22:54:19.760  2021      1   31      Sunday
3 2021-01-31 22:06:00.832  2021      1   31      Sunday
4 2021-01-31 21:51:14.016  2021      1   31      Sunday

In [29]:
df["depth_km"].mean()

np.float64(71.39596524299554)

In [30]:
def check_depth(depth):
    if depth < 70:
        return "Shallow"
    else:
        return "Deep"

df["EQ_depth_flag"] = df["depth_km"].apply(check_depth)

print(df[["depth_km", "EQ_depth_flag"]].head())

   depth_km EQ_depth_flag
0     17.27       Shallow
1    426.71          Deep
2     46.73       Shallow
3     10.00       Shallow
4     10.00       Shallow

In [31]:
df["mag"].describe()

count    119331.000000
mean          4.255898
std           0.610809
min           3.000000
25%           4.000000
50%           4.300000
75%           4.600000
max           8.800000
Name: mag, dtype: float64

In [32]:
def check_magnitude(mag):
    if mag >= 7:
        return "Destructive"
    elif mag >= 6:
        return "Strong"
    else:
        return "Normal"

df["magnitude_flag"] = df["mag"].apply(check_magnitude)

print(df[["mag", "magnitude_flag"]].head())

   mag magnitude_flag
0  4.7         Normal
1  4.1         Normal
2  4.7         Normal
3  4.9         Normal
4  4.0         Normal

In [33]:
df["dmin"]=df["dmin"].fillna(df["dmin"].median())

In [34]:
df=df.drop(columns="deptherror")

In [35]:
df.isnull().sum()

id                     0
time                   0
updated                0
latitude               0
longitude              0
depth_km               0
mag                    0
magType                0
place                  0
status                 0
tsunami                0
alert                  0
felt                   0
cdi                    0
sig                    0
net                    0
code                   0
ids                    0
magNst            119331
magscore          119331
magerror          119331
sources                0
types                  0
nst                    0
dmin                   0
rms                    0
gap                    0
type                   0
Year                   0
month                  0
day                    0
day_of_week            0
EQ_depth_flag          0
magnitude_flag         0
dtype: int64

In [36]:
df.to_csv("earthquake_cleandata.csv",index=False)

In [37]:
df["depth_km"].describe()

count    119331.000000
mean         71.395965
std         122.756055
min          -3.740000
25%          10.000000
50%          21.100000
75%          70.560000
max         683.578000
Name: depth_km, dtype: float64